Exception: rename errno() to get_errno()
On Linux these days errno is a macro which is expanded on compilation.
This makes it impossible to name the method errno(). Therefore it has
been renamed to get_errno().